/* INTRO CINEMATIC — blocked in-engine (not a slideshow). Shots are data: set builder, actors, camera keys, timed events,
   captions/subtitles. Final models/VO/music replace temporary assets without changing sequence logic (audio cue ids are in place).
   Order: Mara rescue → Gabriel rescue → Daniel rescue / Elias injury → family montage → Lantern gathering → massacre →
   Evelyn's sacrifice → Elias & the Hollow vanish → (black) → KEEPITIL → TUITEA → THIRTEEN → HQ. */
(function () {
  const CI = T13.cinema = {}, X = T13.gfx, V = THREE.Vector3;
  let scene, cam, raf = 0, shotI = 0, t = 0, last = 0, actors = {}, done = null, playing = false, fx = [];
  const $ = id => document.getElementById(id);
  const ease = x => x < 0.5 ? 2 * x * x : 1 - Math.pow(-2 * x + 2, 2) / 2;
  const person = (id, x, z, ry, opts = {}) => { const p = T13.people.buildProcedural(id, opts); p.root.position.set(x, 0, z); p.root.rotation.y = ry; scene.add(p.root); p.id = id; return p; };
  const room = (w, d, wall, floor, lights) => { const g = new THREE.Group(); const wm = X.mat({ map: X.wallTex(...wall, 'cine' + wall.join()) }), fm = X.mat({ map: X.tileTex(...floor, 'cinef' + floor.join()) });
    const f = new THREE.Mesh(new THREE.PlaneGeometry(w, d), fm); f.rotation.x = -Math.PI / 2; g.add(f); const c = new THREE.Mesh(new THREE.PlaneGeometry(w, d), X.mat({ color: 0x1a1814 })); c.rotation.x = Math.PI / 2; c.position.y = 3; g.add(c);
    [[0, -d / 2, 0, w], [0, d / 2, Math.PI, w], [-w / 2, 0, Math.PI / 2, d], [w / 2, 0, -Math.PI / 2, d]].forEach(([x, z, ry, len]) => { const m = new THREE.Mesh(new THREE.PlaneGeometry(len, 3), wm); m.position.set(x, 1.5, z); m.rotation.y = ry; g.add(m); });
    scene.add(g); scene.add(new THREE.HemisphereLight(X.col(0x6a7080), X.col(0x2a2018), lights?.hemi ?? 0.35)); (lights?.points || []).forEach(([x, y, z, col, i, d2]) => { const l = new THREE.PointLight(X.col(col), i, d2 || 8, 1.6); l.position.set(x, y, z); scene.add(l); actors['L' + fx.length + x] = l; }); return g; };
  const torch = (p) => { const l = new THREE.SpotLight(X.col(0xfff0d0), 1.6, 12, 0.45, 0.5, 1.2); l.position.set(0.3, 1.3, -0.2); const tg = new THREE.Object3D(); tg.position.set(0, 1.0, -5); p.root.add(l, tg); l.target = tg; };
  const hollow = (x, z, ry, mode = 'full') => { const h = T13.hollow.buildProcedural(); h.root.position.set(x, 0, z); h.root.rotation.y = ry; h.setReveal(mode); scene.add(h.root); return h; };
  const burst = (pos, col = 0xffe2a0, size = 3, secs = 0.8) => { const m = new THREE.Mesh(new THREE.SphereGeometry(0.2, 16, 12), new THREE.MeshBasicMaterial({ color: col, transparent: true, opacity: 0.9, blending: THREE.AdditiveBlending, depthWrite: false })); m.position.copy(pos); scene.add(m); const l = new THREE.PointLight(X.col(col), 3, 10, 1.4); l.position.copy(pos); scene.add(l); fx.push({ m, l, t: 0, secs, size }); };
  const sub = (who, text, ms = 3200) => { const el = $('cinSub'); el.innerHTML = who ? `<b>${who}</b> — ${text}` : text; el.style.opacity = 1; clearTimeout(sub.t); sub.t = setTimeout(() => { el.style.opacity = 0; }, ms); };
  const cap = (text) => { const el = $('cinCap'); el.textContent = text; el.style.opacity = 1; clearTimeout(cap.t); cap.t = setTimeout(() => { el.style.opacity = 0; }, 3200); };
  const walk = (p, to, secs) => ({ p, from: p.root.position.clone(), to, secs, t: 0 });
  /* ------------- SHOTS ------------- */
  const SHOTS = [
    { dur: 8, cap: 'Oregon · 1986', build() { room(8, 12, ['#4a4438', '#8a806a', '#2a2620'], ['#4a4034', '#3a3228'], { hemi: 0.2 }); const e = person('elias', 0.6, 5, Math.PI), v = person('evelyn', -0.6, 5.6, Math.PI); torch(e); torch(v); actors.e = e; actors.v = v; actors.walks = [walk(e, new V(0.6, 0, 1.5), 7), walk(v, new V(-0.6, 0, 2.1), 7)]; },
      cam: [[0, new V(0, 1.4, -3), new V(0, 1.4, 5)], [8, new V(0.3, 1.5, -1.5), new V(0, 1.5, 2)]], ev: [[2, () => T13.audio.creak(2, 2, -3)]] },
    { dur: 14, build() { room(9, 9, ['#4a4438', '#8a806a', '#2a2620'], ['#4a4034', '#3a3228'], { hemi: 0.25, points: [[0, 2.6, 0, 0xffc890, 0.6]] }); actors.e = person('elias', -1.2, 2, Math.PI * 0.95); actors.v = person('evelyn', 1.0, 2.4, Math.PI * 1.05); torch(actors.e); torch(actors.v); actors.h = hollow(0, -2.5, 0, 'shadow'); },
      cam: [[0, new V(3.5, 1.7, 3.5), new V(0, 1.3, -1)], [14, new V(-2.5, 1.5, 4.2), new V(0, 1.4, -1.5)]],
      ev: [[1.5, () => { T13.audio.growl(0, 1.8, -2.5); actors.hunting = true; }], [4, () => { actors.e.p.act('point', new V(0, 1.4, -2.5)); burst(new V(-0.6, 1.4, 0.8), 0xff9a7a, 2.2); T13.audio.ability('gabriel'); sub('ELIAS', 'Stay behind me!'); actors.h.root.position.z -= 0.8; }],
        [7, () => { actors.v.p.setExpr('concern'); burst(new V(1.0, 1.65, 2.3), 0xffe2a0, 1.2, 1.4); T13.audio.ability('mara'); sub('EVELYN', 'That’s not a ghost. It’s wearing one.'); actors.h.setReveal('full'); }], [10, () => { burst(new V(0, 1.4, -2.5), 0xfff0d0, 4, 1.2); actors.hFade = true; T13.audio.sting(); }]] },
    { dur: 10, build() { room(6, 6, ['#4a4438', '#8a806a', '#2a2620'], ['#4a4034', '#3a3228'], { hemi: 0.25, points: [[0, 2.4, 1, 0xffd8a0, 0.5]] }); const closet = new THREE.Mesh(new THREE.BoxGeometry(1.4, 2.4, 0.9), X.mat({ map: X.woodTex('#4a3422', 'closet') })); closet.position.set(0, 1.2, -2.4); scene.add(closet); actors.m = person('mara', 0, -1.7, 0, { child: 0.55 }); actors.m.setExpr('fear'); actors.v = person('evelyn', 0.2, 0.6, Math.PI); actors.e = person('elias', 1.3, 1.4, Math.PI * 1.1); },
      cam: [[0, new V(0.4, 0.9, 0.2), new V(0, 0.75, -1.7)], [10, new V(1.2, 1.1, 0.9), new V(0, 0.8, -1.6)]],
      ev: [[1, () => sub('', '(a child, crying)')], [3, () => sub('MARA (6)', 'It told me where to hide. It said don’t come out.', 3800)], [6.5, () => { actors.v.setExpr('concern'); sub('EVELYN', 'You listened. That’s why you’re alive. Come here, sweetheart.'); actors.m.setExpr('neutral'); }]] },
    { dur: 12, cap: 'Missouri · 1990', build() { room(4, 10, ['#5a4a3a', '#a09070', '#302418'], ['#5a4a3a', '#4a3a2a'], { hemi: 0.38, points: [[0, 2.5, 3, 0xff8a5a, 0.9], [0, 2.3, -2.5, 0x8aa0d0, 0.6]] }); const door = new THREE.Mesh(new THREE.BoxGeometry(1.1, 2.2, 0.08), X.mat({ map: X.woodTex('#5a3a22', 'door2') })); door.position.set(0, 1.1, -3.6); scene.add(door); actors.door = door;
        const sym = new THREE.Mesh(new THREE.PlaneGeometry(0.8, 0.8), new THREE.MeshBasicMaterial({ map: X.tex('cultsym', 256, 256, (g, w, h) => { g.strokeStyle = '#6b0f0f'; g.lineWidth = 8; g.beginPath(); g.arc(128, 128, 70, 0, 7); g.stroke(); for (let i = 0; i < 13; i++) { const a = i / 13 * Math.PI * 2; g.beginPath(); g.moveTo(128 + Math.cos(a) * 50, 128 + Math.sin(a) * 50); g.lineTo(128 + Math.cos(a) * 100, 128 + Math.sin(a) * 100); g.stroke(); } }), transparent: true })); sym.position.set(1.98, 1.7, -1.5); sym.rotation.y = -Math.PI / 2; scene.add(sym);
        actors.g = person('gabriel', 0, -3.1, Math.PI, { child: 0.6 }); actors.g.act('guard'); actors.g.setExpr('fear'); },
      cam: [[0, new V(0, 1.0, 1.5), new V(0, 0.9, -3.4)], [6, new V(-1.0, 1.3, -0.5), new V(0, 0.9, -3.3)], [12, new V(1.2, 1.5, 0.5), new V(1.9, 1.6, -1.5)]],
      ev: [[1, () => { T13.audio.voiceAt(0, 1.6, -5, 1.3, 1.8, 0.25); sub('“MOM”', 'Gabriel, sweetheart. Open the door. It’s cold out here.', 3500); }], [4.5, () => { sub('GABRIEL (7)', 'No. You’re not her.', 2800); actors.g.setExpr('anger'); T13.audio.thump(0, 1, -4, 0.6); }], [7.5, () => { burst(new V(0, 1.2, -4.2), 0xff9a7a, 3); T13.audio.growl(0, 1.6, -5); sub('ELIAS', 'Good boy. Don’t open it — I’m coming through!'); }], [10, () => sub('', '(a mark on the wall — thirteen spokes)', 2000)]] },
    { dur: 14, cap: 'Ohio · 1992', build() { room(7, 7, ['#6a6a5a', '#c8c0a0', '#3a3a2a'], ['#8a8272', '#6f685b'], { hemi: 0.4, points: [[0, 2.6, 0, 0xfff0d0, 0.8]] }); const tbl = new THREE.Mesh(new THREE.BoxGeometry(1.4, 0.05, 0.9), X.mat({ map: X.woodTex('#6a4a2e') })); tbl.position.set(0, 0.78, 0); scene.add(tbl);
        actors.d = person('daniel', -0.9, 0.3, -Math.PI / 2, { child: 0.6 }); actors.s = person('stranger', 1.0, 0.1, Math.PI / 2); actors.s.setExpr('neutral'); actors.hand = hollow(1.35, 0.1, Math.PI / 2, 'limbs'); actors.hand.root.visible = false; actors.e = person('elias', 3, -2.5, Math.PI * 0.75); actors.v = person('evelyn', 3.1, 2.2, Math.PI * 0.3); actors.e.root.visible = actors.v.root.visible = false; },
      cam: [[0, new V(-2.2, 1.1, 1.4), new V(0.5, 1.1, 0)], [5, new V(-0.5, 1.0, 0.9), new V(1.1, 0.9, 0.1)], [9, new V(-2.6, 1.6, 2.6), new V(0.6, 1.2, -0.6)], [14, new V(-1.5, 1.2, 2.2), new V(1.8, 0.4, -1)]],
      ev: [[1, () => sub('UNCLE RAY', 'Your mom said I could pick you up, Danny.', 3000)], [4.5, () => { actors.hand.root.visible = true; sub('DANIEL (8)', 'Uncle Ray has a wedding ring. You don’t.', 3200); actors.d.setExpr('fear'); }], [7.5, () => { actors.s.root.visible = false; actors.hand.setReveal('full'); actors.hand.root.visible = true; T13.audio.sting(); actors.e.root.visible = actors.v.root.visible = true; actors.hunting = true; }],
        [9.5, () => { burst(new V(1.9, 1.5, -1.2), 0xff9a7a, 3); T13.audio.growl(1.4, 1.6, 0); }], [11, () => { T13.cam && null; actors.e.p.setExpr('pain'); actors.eFall = true; burst(new V(2.6, 1.2, -2), 0xff3a2a, 1.5); sub('', '(Elias takes the blow meant for the boy. He will never fight like this again.)', 3200); }]] },
    { dur: 26, build() { room(9, 7, ['#3b2618', '#22352c', '#2a1b10'], ['#4a3222', '#3a2618'], { hemi: 0.45, points: [[0, 2.4, 0, 0xffd9a0, 1.2, 9]] }); const tbl = new THREE.Mesh(new THREE.CylinderGeometry(1.1, 1.1, 0.05, 24), X.mat({ map: X.woodTex('#5a3c24') })); tbl.position.set(0, 0.76, 0); scene.add(tbl);
        const cake = new THREE.Mesh(new THREE.CylinderGeometry(0.2, 0.2, 0.14, 20), X.mat({ color: 0xf0e6d0 })); cake.position.set(0, 0.86, 0); scene.add(cake); for (let i = 0; i < 9; i++) { const c = new THREE.Mesh(new THREE.CylinderGeometry(0.008, 0.008, 0.08, 5), new THREE.MeshBasicMaterial({ color: 0xffe0a0 })); c.position.set(Math.cos(i) * 0.12, 0.97, Math.sin(i) * 0.12); scene.add(c); }
        actors.fam = [['elias', 0, -1.4, 0], ['evelyn', 1.3, -0.4, -Math.PI / 2 + 0.3], ['mara', -1.3, 0.3, Math.PI / 2, 0.75], ['gabriel', 0.9, 1.1, Math.PI * 0.8, 0.72], ['daniel', -0.6, 1.3, Math.PI * 1.1, 0.7]].map(([id, x, z, ry, ch]) => { const p = person(id, x, z, ry, ch ? { child: ch } : {}); p.setExpr('neutral'); return p; }); },
      cam: [[0, new V(3.2, 1.8, 3.2), new V(0, 0.9, 0)], [6, new V(2.4, 1.4, -2.4), new V(-0.6, 1.0, 0.4)], [12, new V(-2.8, 1.3, 1.8), new V(1.2, 1.2, -0.3)], [19, new V(1.8, 1.2, 2.6), new V(0.3, 1.0, 0.5)], [26, new V(0, 2.6, 3.6), new V(0, 0.8, 0)]],
      ev: [[0.5, () => sub('', '(Happy birthday — five voices, badly in tune)', 3500)], [6, () => sub('EVELYN', 'Listen — but don’t automatically believe. Voices can lie, Mara.', 4200)], [12, () => sub('ELIAS', 'Strength is knowing when not to use it, Gabe.', 4000)], [18.5, () => sub('DANIEL', 'Check it twice. Then check who took the photo.', 4000)], [23, () => sub('', 'For a while, they were a family. Lantern was home.', 3000)]] },
    { dur: 12, cap: 'Lantern gathering · November 1998', build() { room(14, 10, ['#3b2618', '#5a4a3a', '#2a1b10'], ['#4a3222', '#3a2618'], { hemi: 0.4, points: [[-3, 2.6, 0, 0xffc880, 1.0, 10], [3, 2.6, 0, 0xffc880, 1.0, 10]] });
        actors.crowd = []; const ids = ['stranger', 'elias', 'stranger', 'evelyn', 'stranger', 'stranger', 'stranger', 'stranger']; ids.forEach((id, i) => { if (id === 'elias' || id === 'evelyn') return; const p = person('stranger', -5 + (i % 5) * 2.4, -3 + Math.floor(i / 5) * 2.2, Math.random() * 6); actors.crowd.push(p); });
        actors.e = person('elias', -0.4, 0.6, Math.PI); actors.v = person('evelyn', 0.5, 0.4, Math.PI); actors.m = person('mara', -0.9, 1.6, Math.PI, { child: 0.93 }); actors.g = person('gabriel', 0.4, 1.8, Math.PI, { child: 0.95 }); actors.d = person('daniel', 1.2, 1.5, Math.PI, { child: 0.92 });
        const cane = new THREE.Mesh(new THREE.CylinderGeometry(0.015, 0.015, 0.95, 6), X.mat({ color: 0x2a1a10 })); cane.position.set(-0.1, 0.47, 0.5); cane.rotation.z = 0.12; scene.add(cane); },
      cam: [[0, new V(0, 2.4, 7), new V(0, 1.2, 0)], [12, new V(1.5, 1.6, 4.2), new V(0, 1.3, 0.8)]], ev: [[2, () => sub('', '(Elias walks with a cane now. He jokes about it. Nobody laughs.)', 3500)], [7, () => sub('EVELYN', 'Everyone came. Every single one of us. …Why does that frighten me?', 4200)]] },
    { dur: 26, build() { room(14, 10, ['#3b2618', '#5a4a3a', '#2a1b10'], ['#4a3222', '#3a2618'], { hemi: 0.2, points: [[-3, 2.6, 0, 0xffc880, 0.35, 10], [3, 2.6, 0, 0xff5a3a, 0.8, 10], [0, 2.4, 2, 0x8aa0d0, 0.5, 8]] });
        actors.crowd = [0, 1, 2, 3, 4, 5].map(i => person('stranger', -5 + i * 2, -2.5, Math.random() * 6)); actors.e = person('elias', -0.5, 0.8, Math.PI); actors.v = person('evelyn', 0.4, 0.3, Math.PI); actors.kids = [['mara', -0.8, 2.2], ['gabriel', 0.1, 2.4], ['daniel', 0.9, 2.2]].map(([id, x, z]) => { const p = person(id, x, z, Math.PI, { child: 0.93 }); p.setExpr('fear'); return p; });
        actors.h = hollow(0, -3.5, 0, 'shadow'); },
      cam: [[0, new V(0, 1.7, 6), new V(0, 1.4, -2)], [8, new V(-3, 1.3, 2.5), new V(0.3, 1.5, -1.5)], [14, new V(2.2, 1.4, 3.2), new V(0, 1.4, 0)], [20, new V(0.8, 1.2, 2.6), new V(0.4, 1.4, 0.2)], [26, new V(0, 2.2, 5), new V(0, 1.2, 0)]],
      ev: [[0.5, () => { T13.audio.power(false); sub('', '(every light in the building dies at once)', 2600); }], [3, () => { T13.audio.voiceAt(-4, 1.6, -2, 1.1, 1.6, 0.2); T13.audio.voiceAt(4, 1.6, -1, 0.9, 1.6, 0.2); sub('VOICES', '“Elias, it’s me—” “Over here—” “Help me—”', 3200); }], [6, () => { actors.crowd.forEach((p, i) => setTimeout(() => { p.root.rotation.z = 1.4; p.root.position.y = 0.3; }, i * 300)); actors.h.setReveal('full'); actors.hunting = true; actors.hWalk = walk(actors.h, new V(0, 0, -0.8), 8); T13.audio.growl(0, 1.8, -3); }],
        [9, () => { actors.e.act('guard'); burst(new V(-0.3, 1.3, 0), 0xff9a7a, 1.4); sub('ELIAS', 'Not them — take me!', 2600); actors.e.setExpr('pain'); }], [13, () => { actors.v.setExpr('concern'); burst(new V(0.4, 1.65, 0.3), 0xffe2a0, 1.2, 1.5); sub('EVELYN', 'It doesn’t want you, Elias. It wants all five of us together. The children.', 4500); }],
        [18, () => { actors.v.root.position.set(0, 0, -0.4); actors.v.act('guard'); burst(new V(0, 1.4, -0.6), 0xffe2a0, 6, 2.2); T13.audio.sting(); sub('EVELYN', 'Take it all. Keep them safe.', 3000); actors.gold = true; }], [21.5, () => { actors.v.root.rotation.x = -1.5; actors.v.root.position.y = 0.25; actors.kids.forEach(k => k.setExpr('pain')); sub('MARA', 'MOM—!', 1800); }]] },
    { dur: 16, build() { room(14, 10, ['#3b2618', '#5a4a3a', '#2a1b10'], ['#4a3222', '#3a2618'], { hemi: 0.16 }); actors.e = person('elias', -0.4, 0, 0); actors.h = hollow(0.6, -1.2, Math.PI, 'full'); actors.hunting = true; actors.kids = [['mara', -1.2, 2.6], ['gabriel', 0, 2.9], ['daniel', 1.1, 2.6]].map(([id, x, z]) => { const p = person(id, x, z, Math.PI, { child: 0.93 }); p.setExpr('fear'); return p; });
        const ring = new THREE.Mesh(new THREE.TorusGeometry(1.4, 0.06, 10, 48), new THREE.MeshBasicMaterial({ color: 0xbfd6ff, transparent: true, opacity: 0, blending: THREE.AdditiveBlending })); ring.position.set(0, 1.5, -2.6); scene.add(ring); actors.ring = ring; const disc = new THREE.Mesh(new THREE.CircleGeometry(1.35, 40), new THREE.MeshBasicMaterial({ color: 0x0a0c18, transparent: true, opacity: 0 })); disc.position.copy(ring.position); scene.add(disc); actors.disc = disc; actors.portalL = new THREE.PointLight(X.col(0x9fb4ff), 0, 12, 1.4); actors.portalL.position.set(0, 1.5, -2.2); scene.add(actors.portalL); },
      cam: [[0, new V(0, 1.4, 5.5), new V(0, 1.5, -1.5)], [8, new V(3, 1.8, 2), new V(0, 1.5, -1.8)], [16, new V(0, 1.3, 4.5), new V(0, 1.2, 1.5)]],
      ev: [[1, () => { actors.portal = true; T13.audio.power(true); sub('ELIAS', 'You want a door? I’ll give you one.', 3200); }], [5, () => { actors.e.act('point', new V(0.6, 1.5, -1.2)); burst(new V(0.3, 1.5, -1.2), 0xbfd6ff, 3); T13.audio.growl(0.6, 1.8, -1.2); }], [7, () => { actors.pull = walk(actors.h, new V(0, 0, -3.2), 3); actors.epull = walk(actors.e, new V(-0.1, 0, -2.9), 3.4); }], [11, () => { actors.close = true; burst(new V(0, 1.5, -2.6), 0xffffff, 6, 1.4); T13.audio.sting(); }], [13, () => sub('', '(and then there were three)', 2600)]] },
    { dur: 3, build() { scene.add(new THREE.AmbientLight(0x000000, 0)); }, cam: [[0, new V(0, 1, 5), new V(0, 1, 0)], [3, new V(0, 1, 5), new V(0, 1, 0)]], ev: [] },
  ];
  CI.SHOTS = SHOTS; CI.duration = () => SHOTS.reduce((a, s2) => a + s2.dur, 0);
  function buildShot(i) { scene = new THREE.Scene(); scene.background = new THREE.Color(0x030304); scene.fog = new THREE.FogExp2(0x050507, 0.04); actors = {}; fx = []; SHOTS[i].build(); t = 0; if (SHOTS[i].cap) cap(SHOTS[i].cap); $('cinFade').style.opacity = 1; setTimeout(() => { $('cinFade').style.opacity = 0; }, 60); }
  const each = f => Object.values(actors).forEach(v => { if (Array.isArray(v)) v.forEach(f); else f(v); });
  function camAt(keys, tt) { let k = 0; while (k < keys.length - 2 && tt > keys[k + 1][0]) k++; const [t0, p0, l0] = keys[k], [t1, p1, l1] = keys[Math.min(k + 1, keys.length - 1)]; const f = t1 > t0 ? ease(Math.min(1, Math.max(0, (tt - t0) / (t1 - t0)))) : 1; cam.position.lerpVectors(p0, p1, f); cam.lookAt(new V().lerpVectors(l0, l1, f)); }
  function loop(now) { if (!playing) return; raf = requestAnimationFrame(loop); const dt = Math.min(0.05, Math.max(0, (now - last) / 1000)); last = now; t += dt; const S = SHOTS[shotI];
    S.ev.forEach(e => { if (!e.fired && t >= e[0]) { e.fired = true; try { e[1](); } catch (err) { console.warn(err); } } });
    each(v => { if (v && v.update && v.root) v.update(dt, v.root.parent ? (v.setReveal ? { speed: 0.4, hunting: !!actors.hunting } : {}) : {}); });
    ['walks'].forEach(k => (actors[k] || []).forEach(w => { w.t += dt; const f = Math.min(1, w.t / w.secs); w.p.root.position.lerpVectors(w.from, w.to, f); w.p.update(0, { speed: f < 1 ? 1.4 : 0 }); }));
    ['hWalk', 'pull', 'epull'].forEach(k => { const w = actors[k]; if (!w) return; w.t += dt; const f = Math.min(1, w.t / w.secs); w.p.root.position.lerpVectors(w.from, w.to, ease(f)); });
    if (actors.hFade && actors.h) { actors.h.root.scale.multiplyScalar(1 - dt * 0.6); }
    if (actors.eFall && actors.e) { actors.e.root.rotation.x = Math.max(-1.2, actors.e.root.rotation.x - dt * 1.4); }
    if (actors.portal && actors.ring) { actors.ring.material.opacity = Math.min(0.9, actors.ring.material.opacity + dt * 0.4); actors.disc.material.opacity = Math.min(0.95, actors.disc.material.opacity + dt * 0.4); actors.ring.rotation.z += dt; actors.portalL.intensity = Math.min(3, actors.portalL.intensity + dt); }
    if (actors.close && actors.ring) { actors.ring.scale.multiplyScalar(1 - dt * 1.2); actors.disc.scale.multiplyScalar(1 - dt * 1.2); if (actors.e) actors.e.root.visible = false; if (actors.h) actors.h.root.visible = false; actors.portalL.intensity *= 1 - dt; }
    fx = fx.filter(f => { f.t += dt; const k = f.t / f.secs; f.m.scale.setScalar(1 + k * f.size * 5); f.m.material.opacity = Math.max(0, 0.9 * (1 - k)); f.l.intensity = Math.max(0, 3 * (1 - k)); if (k >= 1) { scene.remove(f.m, f.l); return false; } return true; });
    camAt(S.cam, t); X.renderer.render(scene, cam);
    if (t >= S.dur) { shotI++; if (shotI >= SHOTS.length) return finish(); buildShot(shotI); }
  }
  function finish() { playing = false; cancelAnimationFrame(raf); $('cinema').classList.add('hidden'); try { const sv = JSON.parse(localStorage.getItem('t13-save') || '{}'); sv.introSeen = true; sv.films = Array.from(new Set([...(sv.films || []), 'intro'])); localStorage.setItem('t13-save', JSON.stringify(sv)); } catch (e) {} const d = done; done = null; d && d(); }
  /* play the intro. First viewing: no skip (it sets up everything). Afterwards: skippable immediately. */
  CI.play = (cb, opts = {}) => { X.initRenderer($('view')); T13.audio.init(); cam = new THREE.PerspectiveCamera(42, innerWidth / innerHeight, 0.05, 60); X.cams.add(cam); done = cb; shotI = opts.from || 0; SHOTS.forEach(s2 => s2.ev.forEach(e => { e.fired = false; }));
    let seen = false; try { seen = !!JSON.parse(localStorage.getItem('t13-save') || '{}').introSeen; } catch (e) {}
    $('cinema').classList.remove('hidden'); $('cinSkip').classList.toggle('hidden', !seen && !opts.allowSkip); $('cinSkip').onclick = () => finish();
    buildShot(shotI); playing = true; last = performance.now(); raf = requestAnimationFrame(loop); };
  CI.isPlaying = () => playing; CI.jump = i => { shotI = i; buildShot(i); };
})();
