/* PokaSnap 2.2.0 (22) C1.6A — generated by tools/release/build.mjs. */
const CACHE = 'pokasnap-ddbcf6905967';
const SHELL = ["./","img/icon-180.png","img/icon-192.png","img/icon-512.png","index.html","js/board.js","js/config.js","js/core.js","js/dance.js","js/data/music.js","js/dioramas.js","js/flight.js","js/gamekit.js","js/landmarks.js","js/main.js","js/props.js","js/pudding.js","js/qa.js","js/race.js","js/raceSim.js","js/radio.js","js/switch.js","js/weekly.js","js/world.js","manifest.webmanifest","v22.css","build.json"];
self.addEventListener('install', e => { e.waitUntil(caches.open(CACHE).then(c => Promise.all(SHELL.map(u => fetch(u, { cache: 'reload' }).then(r => r.ok && c.put(u, r))))).then(() => self.skipWaiting())); });
self.addEventListener('activate', e => { e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k.startsWith('pokasnap-') && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', e => {
  const u = new URL(e.request.url); if (e.request.method !== 'GET' || u.origin !== location.origin) return;
  if (e.request.mode === 'navigate') { e.respondWith(fetch(e.request).catch(() => caches.open(CACHE).then(c => c.match('index.html')))); return; }
  e.respondWith(caches.open(CACHE).then(c => c.match(e.request).then(hit => hit || fetch(e.request))));
});
